apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lab2
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master
        name: itdt-contained-frontend
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: "svslyusarenko"
        - name: REACT_APP_COMPANY_NAME
          value: "itmo"